### PR TITLE
header ui issues, scroll issue fixed, profile icon inclick fixed

### LINKED ISSUE #84: In mobile view profile icon and  signin/signup links in hamburger menu are not clickable
Header- In mobile view profile icon and  signin/signup links in hamburger menu are not clickable, Hamburger Menu content  is not scrollable.

_Originally posted by @sselvara in https://github.com/hlxsites/airindia/issues/82#issuecomment-2074004486_

### PR DESCRIPTION
**Pull request by kalimuthu-a**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #84 

Test URLs:
- Before: https://main--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity
- After: https://header-ui-issues--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity

### CODE REVIEW

File: scripts/scripts.js [hunk 1]
```diff
@@ -170,7 +170,7 @@ async function loadLazy(doc) {
 
   loadCSS(`${window.hlx.codeBasePath}/styles/lazy-styles.css`);
   loadFonts();
-
+  await import('./utils/blockUtils.js');
```
Comment (sselvara) [inline scripts/scripts.js:173]: can this import added immediately after loading the header and footer?

**Review by sselvara — CHANGES_REQUESTED** [review]

File: scripts/scripts.js (hunk 1 above)
Comment (kalimuthu-a) [reply scripts/scripts.js]: Done Subash

**Review by sselvara — APPROVED** [review]
