### PR TITLE
fix to make signin button disappear after login

### LINKED ISSUE #106: Sign-in action available even after login
image

### PR DESCRIPTION
**Pull request by kalimuthu-a**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #106, #107, #108

Test URLs:
- Before: https://main--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity
- After: https://profile-name--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity

### CODE REVIEW

File: scripts/scripts.js [hunk 1]
```diff
@@ -165,6 +166,11 @@ async function loadLazy(doc) {
   const element = hash ? doc.getElementById(hash.substring(1)) : false;
   if (hash && element) element.scrollIntoView();
 
+  // Auth scripts
+  await loadScript('/scripts/auth/msal.js');
+  await loadScript('/scripts/auth/authConfig.js');
+  await loadScript('/scripts/auth/authRedirect.js');
```
Comment (sselvara) [inline scripts/scripts.js:172]: Loading this script this will have impact on booking widget's `join now` and signin links as the markup is loaded in delayed.js and listener will not be added to those links.

**Review by sselvara — CHANGES_REQUESTED** [review]

**Review by sselvara — APPROVED** [review]
