### PR TITLE
Adobe data layer fixes

### LINKED ISSUE #75: Click event tracking on footer elements to be added as per the TSD doc.
@kalimuthu-a  Click event tracking on footer elements to be added as per the TSD doc.

_Originally posted by @sselvara in https://github.com/hlxsites/airindia/issues/74#issuecomment-2058294725_

### PR DESCRIPTION
**Pull request by kalimuthu-a**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #75 

Screenshot of the click data layer event
image

Test URLs:
- Before: https://main--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity
- After: https://adobe-data-layer-fixes--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity

### CODE REVIEW

File: blocks/header/header.js [hunk 1]
```diff
@@ -352,6 +354,16 @@ function globalEscapeHandler(e) {
   hideProfileInfo();
 }
 
+function AddAdobeLaunchLoadedHandler() {
```
Comment (sselvara) [inline blocks/header/header.js:357]: use capitalCase for function names

File: scripts/analytics.js [hunk 2]
```diff
@@ -51,3 +91,36 @@ export function pushPageLoadedAnalytics() {
   };
   pushToAdobeDataLayer(dataLayerObj);
 }
+
+function AddclickEventToLinks() {
```
Comment (sselvara) [inline scripts/analytics.js:95]: use capitalCase for function names

File: scripts/analytics.js [hunk 3]
```diff
@@ -51,3 +91,36 @@ export function pushPageLoadedAnalytics() {
...
+        ...(isImage && { clickIcon: link.getAttribute('title') || link.textContent }),
+        type: 'other',
+        URL: link.href,
+      };
+      pushFooterLinkClickAnalytics(dataLayerObj);
+    }
+  });
+}
+
+function AddAdobeLaunchLoadedHandler() {
```
Comment (sselvara) [inline scripts/analytics.js:120]: use capitalCase for function names

File: scripts/delayed.js [hunk 4]
```diff
@@ -50,7 +56,7 @@ async function loadCookieConsentManager() {
 
 await loadCookieConsentManager();
 await loadAdobeLaunch();
-pushPageLoadedAnalytics();
+// pushPageLoadedAnalytics();
```
Comment (sselvara) [inline scripts/delayed.js:59]: this line should be uncommented to track pageLoad event

**Review by sselvara — CHANGES_REQUESTED** [review]

**Review by sselvara — APPROVED** [review]
